# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # dev 전용
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  redis:
    image: redis:7-alpine
    networks:
      - private

  accounting-api:
    build: ./accounting-api
    ports:
      - "8000:8000"
    volumes:
      - ./shared/uploads:/app/shared/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - public
      - private
    restart: always

  accounting-processor:
    build: ./accounting-processor
    env_file: .env
    volumes:
      - ./shared/uploads:/app/shared/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - private
    restart: always

volumes:
  postgres_data:

networks:
  public:
  private:
